# -*- coding: utf-8 -*-
"""New AI Image Recognizer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lh8Ia-mXILWZlCMd_JWdvW5E-dh0lOlx
"""

!pip install flask flask-ngrok transformers Pillow

from transformers import BlipProcessor, BlipForConditionalGeneration
from PIL import Image
import torch
import os

processor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base")

from flask import Flask, request, render_template_string
from flask_ngrok import run_with_ngrok
import io

app = Flask(__name__)
run_with_ngrok(app)  # This makes your app public

html_template = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pictionary AI</title>
    <style>
        body { font-family: 'Comic Sans MS', cursive, sans-serif; background: #ffe; padding: 20px; text-align: center; }
        h1 { color: #ff6600; }
        button, input { margin: 10px; font-size: 1.2em; }
        #timer { font-size: 2em; color: red; }
    </style>
    <script>
        let timer;
        function startTimer() {
            let countdown = 60;
            document.getElementById('timer').innerText = countdown + ' seconds left!';
            timer = setInterval(function() {
                countdown--;
                document.getElementById('timer').innerText = countdown + ' seconds left!';
                if (countdown <= 0) {
                    clearInterval(timer);
                    alert("Time's up! Now upload your image.");
                }
            }, 1000);
        }
    </script>
</head>
<body>
    <h1>🎨 Pictionary AI 🎉</h1>
    <p><strong>Instructions:</strong></p>
    <p>1. Click 'Start' to get your drawing prompt.<br>
       2. Open the Procreate app.<br>
       3. Draw your image and take a screenshot/photo within 1 minute.<br>
       4. Click 'Choose File' and upload your drawing.<br>
       5. See if AI can guess what you drew!</p>

    {% if prompt %}
        <h2>Your Drawing Prompt: <em>{{ prompt }}</em></h2>
        <div id="timer"></div>
        <script>startTimer();</script>
    {% endif %}

    <form method="POST" enctype="multipart/form-data">
        <button name="start" type="submit">🎲 Start</button><br>
        <input type="file" name="image"><br>
        <button type="submit">📤 Upload</button>
    </form>

    {% if caption %}
        <h2>AI's Guess: 🤖 "{{ caption }}"</h2>
        <form method="POST">
            <button name="play_again" type="submit">🔁 Play Again</button>
        </form>
    {% endif %}
</body>
</html>
"""

# List of fun prompts
prompts = [
    "a flying elephant", "a dinosaur at the beach", "a cat riding a skateboard",
    "a monster eating spaghetti", "a robot watering flowers", "a unicorn in space"
]

import random

@app.route("/", methods=["GET", "POST"])
def index():
    prompt = caption = None
    if request.method == "POST":
        if 'start' in request.form:
            prompt = random.choice(prompts)
        elif 'image' in request.files:
            image_file = request.files['image']
            if image_file:
                image = Image.open(io.BytesIO(image_file.read())).convert("RGB")
                inputs = processor(images=image, return_tensors="pt")
                out = model.generate(**inputs)
                caption = processor.decode(out[0], skip_special_tokens=True)
        elif 'play_again' in request.form:
            prompt = random.choice(prompts)

    return render_template_string(html_template, prompt=prompt, caption=caption)

app.run()

